### ISSUE TITLE
Question about multiple locations

### ISSUE THREAD

**Issue by stevehoek** [valiquette/homebridge-rachio-irrigation#51]
Just found this plugin after using kcharwood's for awhile at my home.  Now I have another Rachio at a cottage and am finding it doesn't work with multiple homes.  Yours seems to support that.  Can you tell me if each plugin instance needs a unique external webhook port?  In other words, use 12453 at home and 12454 at the cottage?  Or does that not matter?

**Comment by valiquette** [comment]
Hard to say not know exactly what you network situation looks like. 
The plugin will not allow more than one internal port, it does not even support configuring more than one as it will by design ignore incoming request that do not match the internal port or the basic auth (if used). 
It should just work if one site works both sites should work. 
The intended use case is that the 2nd location had its own homebridge instance and the only webhooks difference required is the external IP.
If you are running two homebridge instances off the same router (external ip), then yes you would need unique ports for both internal and external.

You may want to try and clear web hook in case there is something off with what is currently configured. 
If you can't get it working I may need to see your config and the debug log when it loads.
viewing the debug logs while it loads or while you start stop zone from the rachis app could be very helpful to your trouble shooting this.

**Comment by stevehoek** [comment]
> The intended use case is that the 2nd location had its own homebridge instance and the only webhooks difference required is the external IP.

yeah these are two separate locations, different routers, different external IP's.  Each location has its own RPi running Homebridge.  I didnt know if Rachio's API would get confused if there were two webhooks using the same port, but as you say the external IP would be different, so my concern is probably unfounded.

Thanks for your work on this plugin!

**Comment by valiquette** [comment]
Your good, the webhooks are based on device ID on the Rachio end

**Comment by stevehoek** [comment]
I think I have to name the plugin differently at each location, because it appears if you leave it as "Rachio" that is being sent to the Rachio API as "Homebridge-Rachio" in both cases... something for the README maybe?

I have named mine Rachio-Cottage and Rachio-Home and it seems to be working (apart from the webhook basic auth that I have another issue opened about)

**Comment by valiquette** [comment]
That could be the plugin name is used as the external-ID with Rachio, I don't if that make a difference not the sending end but it is used on the plugin side to filter out un wanted messages.
