### ISSUE TITLE
Commands Repeating

### ISSUE THREAD

**Issue by nzdew** [valiquette/homebridge-rachio-irrigation#59]
Hi there.

When I turn on a zone the command repeats continuously.  It's used up all of my Webhook relays in about 5 minutes...

The also triggers repeated notifications on my Rachio app until I turn the zone off.  This command also repeats.

Help please!

**Comment by valiquette** [comment]
You will have to provide more details, there is nothing obvious that comes to mind. Please enable debug logging and attach logs that capture this.

**Comment by nzdew** [comment]
Sent from my iPhoneOn 29/09/2023, at 21:12, valiquette ***@***.***> wrote:﻿
You will have to provide more details, there is nothing obvious that comes to mind. Please enable debug logging and attach logs that capture this.

**Comment by vmiyoshi** [comment]
I have the same problem. I think it maybe iOS related. I only see it when I try from my iPhone/iPad from within the Home app. This may be a iOS 17 thing. I had been using my Rachio system with the homekit integration even though it was said they removed support for it, however after I upgraded to iOS 17 I noticed I couldn't start my sprinklers manually from the home app again on my iPhone or iPad, but it was still working perfectly from the watch. I removed my Rachio system from homekit this morning, and installed this plugin into my homebridge setup. I noticed the problem @nzdew described straight away. Initiating zone manually in the home app on the iPhone/iPad shows that its starting the zone "simulated-webhook" many times and I get like 10 notifications from the Rachio app (very annoying...lol), also Siri can't find the accessory when I say "water backyard" which is strange because she ask if I mean backyard or backyard side sprays, but still errors. However I have no problems initiating from the watch, It shows the command given one time in the logs (which is perfect). Also if I ask Siri on my Mac's, or HomePods to "water backyard" it works no problem.

**Comment by valiquette** [comment]
I see the same thing on different irrigations app, after the upgrade to IOS  17,  the home app on Sonoma is fine. I will have to see what is going on and see if there is any way to work around it.

**Comment by valiquette** [comment]
I saw this in Sonoma too, it is a change tied to the behavior of how you start a zone. In IOS if you "tap" the zone on/off everything works fine, if you "slide" the zone on or off home app send multiple set commands, like change brightness on a bulb. I add a check to look for these duplicates and this should be working like it did in the past.
Please let me know
